from app.schemas.auth import LoginRequest, LoginResult, Role, UserInfo
from app.schemas.catalog import AudienceRead, ChannelRead, CreativeRead, ProductRead
from app.schemas.campaign import (
    CampaignCreate,
    CampaignList,
    CampaignRead,
    CampaignStatus,
    CampaignUpdate,
    ConversionGoal,
    GoalField,
    GoalParseResult,
    StructuredGoal,
)
from app.schemas.strategy import (
    AdGroupPlan,
    ChannelChoice,
    EvidenceType,
    StrategyDetail,
    StrategyEvidenceRead,
    StrategyPlan,
    StrategyRead,
    StrategyStatus,
    StrategyConfirmResult,
)

from app.schemas.ad_task import (
    AdGroupStatusRead,
    AdGroupTaskRead,
    AdPlanTaskRead,
    AdTaskCreateRequest,
    AdTaskCreateResult,
    AdTaskStatusResult,
    KeywordRead,
)

from app.schemas.metric import (
    BudgetConsumptionRead,
    BudgetTargetType,
    CampaignBudgetResult,
    MetricDimension,
    MetricSyncError,
    MetricSyncResult,
    MetricTrendPoint,
    MetricTrendResult,
    MetricTrendSeries,
    MetricTrendWindow,
    RealtimeMetric,
    RealtimeMetricResult,
)

__all__ = [
    "CampaignCreate",
    "CampaignList",
    "CampaignRead",
    "CampaignStatus",
    "CampaignUpdate",
    "ConversionGoal",
    "LoginRequest",
    "LoginResult",
    "Role",
    "UserInfo",
    "AudienceRead",
    "ChannelRead",
    "CreativeRead",
    "GoalParseResult",
    "ProductRead",
    "StructuredGoal",
    "GoalField",
    "GoalParseResult",
    "StructuredGoal",
    "AdGroupPlan",
    "ChannelChoice",
    "EvidenceType",
    "StrategyDetail",
    "StrategyEvidenceRead",
    "StrategyPlan",
    "StrategyRead",
    "StrategyStatus",
    "StrategyConfirmResult",
    "AdGroupTaskRead",
    "AdPlanTaskRead",
    "AdTaskCreateRequest",
    "AdTaskCreateResult",
    "KeywordRead",
    "AdTaskStatusResult",
    "AdGroupStatusRead",
    "BudgetConsumptionRead",
    "BudgetTargetType",
    "CampaignBudgetResult",
    "MetricSyncError",
    "MetricSyncResult",
    "MetricDimension",
    "RealtimeMetric",
    "RealtimeMetricResult",
    "MetricTrendPoint",
    "MetricTrendResult",
    "MetricTrendSeries",
    "MetricTrendWindow",
]
