import http from './http'

export const getCampaigns = (params) => http.get('/campaigns', { params })
export const getProducts = () => http.get('/products')
export const createCampaign = (data) => http.post('/campaigns', data)
export const updateCampaign = (id, data) => http.put(`/campaigns/${id}`, data)
export const parseGoal = (id) => http.post(`/campaigns/${id}/parse-goal`)
export const getCampaign = (id) => http.get(`/campaigns/${id}`)
export const getStrategy = (id, config) => http.get(`/campaigns/${id}/strategy`, config)
export const generateStrategy = (id) => http.post(`/campaigns/${id}/strategy/generate`)
export const confirmStrategy = (id) => http.post(`/campaigns/${id}/strategy/confirm`)
export const getAudiences = () => http.get('/audiences')
export const getCreatives = () => http.get('/creatives')
export const getChannels = () => http.get('/channels')
export const createAdTasks = (id, data) => http.post(`/campaigns/${id}/ad-tasks/create`, data)
export const getAdTasks = (id) => http.get(`/campaigns/${id}/ad-tasks`)
export const syncAdTaskStatus = (id) => http.get(`/ad-tasks/${id}/status`)
export const getRealtimeMetrics = (id, dimension) => http.get(`/campaigns/${id}/metrics/realtime`, { params: { dimension } })
export const getMetricTrend = (id, dimension, window) => http.get(`/campaigns/${id}/metrics/trend`, { params: { dimension, window } })
export const getCampaignBudget = (id) => http.get(`/campaigns/${id}/budget`)
export const syncCampaignMetrics = (id) => http.post(`/campaigns/${id}/metrics/sync`)
export const getAnomalies = (id) => http.get(`/campaigns/${id}/anomalies`)
export const scanAnomalies = (id) => http.post(`/campaigns/${id}/anomalies/scan`)
export const getAnomalyCause = (id, config) => http.get(`/anomalies/${id}/cause`, config)
export const analyzeAnomalyCause = (id) => http.post(`/anomalies/${id}/cause/analyze`)
export const getSuggestions = (id, config) => http.get(`/anomalies/${id}/suggestions`, config)
export const generateSuggestions = (id) => http.post(`/anomalies/${id}/suggestions/generate`)
export const submitSuggestionApproval = (id) => http.post(`/suggestions/${id}/submit-approval`)
export const getApprovals = (params) => http.get('/approvals', { params })
export const approveApproval = (id, opinion) => http.post(`/approvals/${id}/approve`, { opinion })
export const rejectApproval = (id, reason) => http.post(`/approvals/${id}/reject`, { reason })
export const getActionRecords = (campaignId) => http.get('/actions', { params: { campaign_id: campaignId } })
export const getActionRecord = (id) => http.get(`/actions/${id}`)
export const rollbackAction = (id) => http.post(`/actions/${id}/rollback`)
export const executeApprovalAction = (id) => http.post(`/approvals/${id}/execute`)
